name: Cakenaysh
version: '${project.version}'
main: com.stelios.cakenaysh.Cakenaysh
api-version: 1.20
authors: [Stelios]
description: Main plungin for the Cakenaysh Minecraft Server
commands:
  heal:
    description: Heals the player to max health.
    permission: op
  vanish:
    description: Makes the player undetectable and invisible.
    permission: op
  giveItem:
    description: Gives the player the specified item.
    syntax: /giveitem <player> <item> <amount>
    permission: op
  setAttribute:
    description: Sets the specified attribute to the specified value.
    syntax: /setattribute <player> <attribute> <value>
    permission: op
  addAttribute:
    description: Adds the specified value to the specified attribute.
    syntax: /addattribute <player> <attribute> <amount>
    permission: op
  getAttributes:
    description: Gets the attributes of the specified player.
    syntax: /getattributes <player>
    permission: op
  resetAttributes:
    description: Resets the attributes of the specified player.
    syntax: /resetattributes <player>
    permission: op
